steps:
  # Build and push API backend
  - name: 'gcr.io/cloud-builders/docker'
    args: 
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ollama-api:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ollama-api:latest'
      - '-f'
      - 'api/Dockerfile.backend'
      - './api'
    id: 'build-api'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama-api:$SHORT_SHA']
    id: 'push-api'
    waitFor: ['build-api']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama-api:latest']
    waitFor: ['build-api']

  # Build and push Frontend
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ollama-frontend:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ollama-frontend:latest'
      - '-f'
      - 'frontend/Dockerfile.frontend'
      - './frontend'
    id: 'build-frontend'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama-frontend:$SHORT_SHA']
    id: 'push-frontend'
    waitFor: ['build-frontend']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama-frontend:latest']
    waitFor: ['build-frontend']

  # Build and push Ollama
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ollama:$SHORT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/ollama:latest'
      - '-f'
      - 'Dockerfile.ollama'
      - '.'
    id: 'build-ollama'

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama:$SHORT_SHA']
    id: 'push-ollama'
    waitFor: ['build-ollama']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama:latest']
    waitFor: ['build-ollama']

images:
  - 'gcr.io/$PROJECT_ID/ollama-api:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/ollama-api:latest'
  - 'gcr.io/$PROJECT_ID/ollama-frontend:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/ollama-frontend:latest'
  - 'gcr.io/$PROJECT_ID/ollama:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/ollama:latest'

options:
  machineType: 'E2_HIGHCPU_8'

timeout: '1800s'
