steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/ollama', '-f', 'Dockerfile.ollama', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/ollama']
images:
  - 'gcr.io/$PROJECT_ID/ollama'
