name: Deploy to Google Cloud Run

on:
  push:
    branches:
      - main

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: ${{ secrets.GCP_REGION }}
  SERVICE_NAME: ollama-provider

jobs:
  deploy:
    name: Deploy to Google Cloud Run
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Google Auth
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Set up Cloud SDK
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: Configure Docker
      run: gcloud auth configure-docker --quiet

    - name: Build and Push API Image
      run: |-
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME-api:latest ./api
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME-api:latest

    - name: Build and Push Frontend Image
      run: |-
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME-frontend:latest ./frontend
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME-frontend:latest
    
    - name: Build and Push Ollama Image
      run: |-
        docker build -t gcr.io/$PROJECT_ID/$SERVICE_NAME-ollama:latest -f Dockerfile.ollama .
        docker push gcr.io/$PROJECT_ID/$SERVICE_NAME-ollama:latest

    - name: Deploy API to Cloud Run
      run: |-
        gcloud run deploy $SERVICE_NAME-api \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME-api:latest \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars "POSTGRES_DSN=${{ secrets.POSTGRES_DSN }}" \
          --set-env-vars "REDIS_URL=${{ secrets.REDIS_URL }}" \
          --set-env-vars "OLLAMA_BASE_URL=http://$SERVICE_NAME-ollama:11434" \
          --set-env-vars "JWT_SECRET=${{ secrets.JWT_SECRET }}" \
          --set-env-vars "OAUTH_CLIENT_ID=${{ secrets.OAUTH_CLIENT_ID }}" \
          --set-env-vars "OAUTH_CLIENT_SECRET=${{ secrets.OAUTH_CLIENT_SECRET }}" \
          --set-env-vars "ADMIN_EMAIL=admin_ibrahim@zyniq.solutions" \
          --set-env-vars "PROMETHEUS_MULTIPROC_DIR=/tmp/prom" \
          --set-env-vars "OLLAMA_MODELS=${{ secrets.OLLAMA_MODELS }}"

    - name: Deploy Frontend to Cloud Run
      run: |-
        gcloud run deploy $SERVICE_NAME-frontend \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME-frontend:latest \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated

    - name: Deploy Ollama to Cloud Run
      run: |-
        gcloud run deploy $SERVICE_NAME-ollama \
          --image gcr.io/$PROJECT_ID/$SERVICE_NAME-ollama:latest \
          --platform managed \
          --region $REGION \
          --allow-unauthenticated \
          --set-env-vars "OLLAMA_MODELS=${{ secrets.OLLAMA_MODELS }}"
